### ISSUE TITLE
Newcomer Dinner information

### ISSUE THREAD

**Issue by yo-bj** [code4lib/2020.code4lib.org#110]
Hi all,

The Social Activities Committee completed a first draft of restaurants and transportation information. In previous years the website linked to the Google document listing the restaurant signups, but in other years the website listed the restaurants as well as linked to the signup document. We wanted to check in to find out if the website committee is thinking about doing a list of restaurants on the site this year so we can create a spreadsheet/CSV file (or whatever file type you choose) for the website list.

Otherwise, we're fine with providing links to the signups!

**Comment by phette23** [comment]
A list of restaurants for the site would be pretty cool! I think we could add this somewhat easily. We could put a "restaurants.csv" file in our _data directory and then use it to display a list somewhere else. You could put whatever you like in the CSV. I'm guessing name, address, description, & website at the very least and then perhaps some booleans for veggie/vegan-friendly would make sense too.
To be clear; the restaurant data would be _in addition_ to the signups link? Displaying a list is easy but I don't think we could do signups on the site, at least not very easily.

**Comment by yo-bj** [comment]
Yes, in addition to the signups link 😄 I think someone did a list setup a few years back - 2016 or 2017, I think?

How much lead time do you et al. need for the spreadsheet before we open the signup doc?

**Comment by phette23** [comment]
I think a week would be plenty of time for us. We meet on Thursday and could discuss it then. I'm assuming no one will get to anything next week though because of vacations.

For reference, here's the 2017 site with its table of restaurants: https://2017.code4lib.org/venue/dinner.html
Here's the corresponding code: https://github.com/code4lib/2017.code4lib.org/blob/master/venue/dinner.html#L163-L192

That seems quite simple. If we have the time and really want to get fancy, we could add some filtering/facets or ordering to the table but it's functional as is. The spreadsheet fields are:

- name
- url
- type
- neighborhood
- distance (number)
- takes reservations (boolean)
- veggie friendly (boolean)

If I'm honest I think an address is far more valuable than the neighborhood, since that assumes that people are familiar with local neighborhoods.

**Comment by dzoladz** [comment]
I can work on implementing a restaurant list in January.

**Comment by yo-bj** [comment]
Hi all - Here is a spreadsheet with the current list: https://docs.google.com/spreadsheets/d/1c_3rTEI3dqhURPYgIY_JD5Plp6AdGfABpbAEL0jxOVs/edit?usp=sharing. One of the committee members had access to a website that rates local restaurants on accessibility, but the majority of the restaurants listed here were not on the website. We plan to enter what we have in the signup document, but I'll leave it up to you if you want to include that information in the table

**Comment by dzoladz** [comment]
I'll give this a whirl over the next few days. I'll be in touch shortly.

**Comment by dzoladz** [comment]
#112 is open for review

**Comment by yo-bj** [comment]
Thank you everyone.

I had a chance to review some of the location information today, and found that there are data quality issues surrounding the distance from the hotel to the restaurants. I will be asking my committee to review and revise the column entries and will get back to you when we are done with our review.

**Comment by yo-bj** [comment]
The updated spreadsheet is at https://docs.google.com/spreadsheets/d/13OvbS6xBeXuW4QeHcasuQgAgR7-ncqmzwc_Q64WVBr4/edit?usp=sharing. This spreadsheet has the correct distance information.

Apologies again for the bad data in the first spreadsheet and please let me know if there are any questions!

**Comment by dzoladz** [comment]
@yo-bj  @phette23 I'll work on updating the data
