### ISSUE TITLE
Skipped heading on Conference Planning Timeline

### ISSUE THREAD

**Issue by jscaffrey** [code4lib/2020.code4lib.org#150]
Ref #21 [Conference Planning Timeline](https://2020.code4lib.org/schedule/timeline) skips from `<h1>` to `<h3>`. Change structure to h2, h3, h4 (reference: https://a11yproject.com/checklist/#section-headings), and [add bootstrap classe](https://getbootstrap.com/docs/4.0/content/typography/)s (e.g. `class="h2"`) to preserve styling if desirable.

**Comment by phette23** [comment]
This is the one that's tricky because it's included multiple places (the file itself is _includes/homepage/pre_conference.html). On /schedule/timeline there's only an h1 "Conference planning timeline" then h2 is skipped, but on the home page in the pre-conference display there's an h1 "code4lib 2020 Pittsburgh" then an h2 "The conference for people who code for libraries." the finally the include. So we either need to rethink the home page structure or add logic in the include so it knows where it's being used and adjusts.

**Comment by jscaffrey** [comment]
I think the simplest way to resolve would be to use h2 in the include but style it like an h3. I'll move forward with that, but I'm flexible.
