### ISSUE TITLE
Instagram link broken

### ISSUE THREAD

**Issue by jscaffrey** [code4lib/2020.code4lib.org#151]
Found when crawling for accessibility issues - [Attend Code4Lib](https://2020.code4lib.org/general-info/attend) contains a broken link for Instagram

**Comment by phette23** [comment]
Hmm the same link structure works but only if there's been a post with that hashtag, see last year: https://www.instagram.com/explore/tags/c4l19/ so we can't use the URL until there's been a post. I feel like we should just remove the link then since waiting to update it each year will be hard to remember to do.
