### ISSUE TITLE
Create a post-conference layout

### ISSUE THREAD

**Issue by kaitlinnewson** [code4lib/2020.code4lib.org#153]
For the last couple of years we've wanted to make a post-conference home page layout that would be displayed once the conference ends, but we didn't have the time - maybe this can be the year we do it?

This layout could include things like links to slides/video, a message about the conference being over, and where to look for information about next year's conference.

**Comment by phette23** [comment]
These are the main things I want to highlight:

- slides repository
- youtube videos
- link to post-conference survey
- next year's Code4Lib

I also think we could take time after the con to add slides to each talk post. It's tedious but won't take that long. My immediate idea is just to re-purpose the peri-conference display but with slightly different iconography—rather than presenting "cards" for each conference day, present a row or two of cards for the slide repo & youtube videos, with a sort of "what's next" alert with text thanking everyone for attending, linking to a survey, and displaying all the proposals for next year.

**Comment by phette23** [comment]
I've been _buried_ under online learning work until now but should have some bandwidth for this issue this week.

**Comment by phette23** [comment]
The way I'm structuring things, I want to turn the AM/PM choices into a choice of "icon". There are three default cards so here are the (public domain) icons I'm considering:

**video**:
- Iconathon "Film Preservation" https://thenounproject.com/Iconathon1/uploads/?i=21034
- Public Domain Nouns "Video Camera" https://thenounproject.com/term/video-camera/637/
- or make my own simple play button e.g. like
![play-icon svg](https://user-images.githubusercontent.com/1024833/78713730-96b18080-78cf-11ea-93d4-86e57a4ed16b.png)

**slides**:
- USPTO "prior art" https://thenounproject.com/USPTO/collection/uspto-intellectual-property-symbols/?i=201428
- USPTO "stem" https://thenounproject.com/USPTO/collection/uspto-intellectual-property-symbols/?i=201437

**what's next**:
- Iconathon "Hackathon" https://thenounproject.com/Iconathon1/collection/neighborhoods/?i=6324
- Iconathon "Community Mapping" https://thenounproject.com/Iconathon1/uploads/?i=8677

**Comment by phette23** [comment]
First draft here, work on `postcon` branch:

<img width="1166" alt="Screen Shot 2020-04-07 at 3 18 17 PM" src="https://user-images.githubusercontent.com/1024833/78724905-43492d80-78e3-11ea-912f-a8c8c02a687f.png">

Any thoughts? I found the header/subtitle kind of redundant, not sure how to handle them, the second card here shows what it looks like if I leave the subtitle empty.

**Comment by dzoladz** [comment]
I'm going to push a few minor modifications to the styling and interaction feedback. Feel free to disregard.
